# Generated by Django 4.0.3 on 2023-12-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_answer_author_answer_modify_date_question_author_and_more'),
        ('pybo', '0004_answer_modify_date_question_modify_date'),
    ]

    operations = [
    ]
