# Generated by Django 4.0.3 on 2023-12-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
