# Generated by Django 4.0.3 on 2023-12-17 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='n_input_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 5, 49, 22, 585503, tzinfo=utc), verbose_name='date published'),
        ),
    ]
