# Generated by Django 4.0.3 on 2023-12-17 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_question_attachment_alter_notices_n_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='n_input_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 6, 10, 30, 401887, tzinfo=utc), verbose_name='date published'),
        ),
    ]
