# Generated by Django 4.0.3 on 2023-12-17 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_alter_notices_n_input_date_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AlterField(
            model_name='notices',
            name='n_input_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 6, 35, 18, 872157, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
