# Generated by Django 4.0.3 on 2023-12-17 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0019_alter_notices_n_input_date_alter_question_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='n_input_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 7, 25, 2, 115973, tzinfo=utc), verbose_name='date published'),
        ),
    ]
